config/routes.rb
Rails.application.routes.draw do
  match 'pokreni-akciju', to: 'events#new', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get 'akcije/:id/potvrdi', to: "events#potvrdi"

  get 'akcije/:id' => 'events#show', as: :event
  get 'about' => 'static_pages#about'

  devise_for :users
  resources :events, path_names: {index: 'akcije'} do
    member do
      get 'register'
    end
  end
  get '/register' => 'static_pages#registracija', as: :registracija
  root 'static_pages#feed'

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  before_create :create_slug

  field :name, type: String
  field :date, type: String

  field :adresa, type: String
  field :grad, type: String
  field :telefon

  field :lat
  field :lon

  field :location, type: String
  field :description, type: String
  field :category, type: String
  field :priority, type: String
  field :registrations, type: Integer, default: 0
  field :tag, type: String
  field :slug, type: String

  def register
    self.registrations += 1
    self.save
  end

  def create_slug
    self.slug = self.name.parameterize
  end


end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable

  field :name
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
   class << self
    def serialize_from_session(key, salt)
      record = to_adapter.get(key[0]["$oid"])
      record if record && record.authenticatable_salt == salt
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :register]
  before_action :authenticate_user!, only: [:new,:create,:update, :destroy]


  # GET /events
  # GET /events.json
  def index
    @events = Event.all.sort(created_at: -1)
  end

  def potvrdi
    @event = Event.find(params[:id])
    redirect_to @event, notice: 'Vasa Akcija Je Potvrdjena. Shareujte akciju na FB kako bi povecali odaziv. '
  end
  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @user = current_user
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Email sa verifikacijom vam je poslat na vasu email adresu. Molimo potvrdite' }
        format.json { render :show, status: :created, location: @event }
        EventsMailer.create_event(@user).deliver
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def register
    @event.registrations += 1
    @event.save
    redirect_to @event, notice: 'Uspesno ste se prijavili!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :location, :description, :category, :priority, :tag, :registrations, :adresa, :grad, :telefon)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    reset_session
    redirect_to root_url, :notice => 'Uspesno ste se izlogovali'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def landing_Page
  end

  def feed
    @events = Event.all.sort(created_at: -1)
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <div class="large-12 columns">
  <%= f.input :name, label: false, placeholder: "Naziv Akcije" %>
  </div>
  <div class="large-4 columns">
  <%= f.input :date, label: false, placeholder: "Datum i Vreme"  %>
  </div>
  <div class="large-4 columns">
  <%= f.input :category, label: false, placeholder: "Kategorija", collection: [
    "Fizički rad – teži",
    "Fizički rad – lakši",
    "Odeća i obuća",
    "Deca - odeća i obuća",
    "Bebe - odeća i obuća",
    "Hrana i voda",
    "Bebe – Hrana, lekovi i higijena",
    "Lekovi i higijena",
    "Posteljina i peškiri"]  %>
  </div>
  <div class="large-4 columns">
  <%= f.input :priority, label: false, placeholder: "Prioritet"  %>
  </div>
  <div class="large-12 columns">
  <%= f.input :description, label: false, placeholder: "Opis Akcije", as: :text  %>
  </div>
  <hr>
  <div class="large-12 columns">
  <%= f.input :adresa, label: false, placeholder: "Adresa ili Objekat gde se odrzava akcije"  %>
  </div>
  <div class="large-12 columns">
  <%= f.input :grad, label: false, placeholder: "Grad"  %>
  </div>
  <div class="large-12 columns">
  <%= f.input :telefon, label: false, placeholder: "Kontakt Telefon"  %>
  </div>
  <div class="large-12 columns">
  <%= f.button :submit, "Pokreni Akciju" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row">
  <div class="large-4 columns">
    <section id="courses-banner-large">
      <div class="row">
        <div class="large-12 columns banner-image">
          <%= image_tag 'ikonica.png' %>
        </div>
        <div class="large-12 columns banner-info">
          <h3>Uključite se!</h3>
          <p>Odaberite aktuelnu akciju prema sopstvenim mogućnostima i pomozite Vašim sugrađanima.</p>
          <a href="#" class="button">Saznaj Vise »</a>
          <hr>
        </div>
      </div>
    </section>
  </div>
  <div class="large-8 small-12 columns">
    <dl class="sub-nav">
      <dt>Filter:</dt>
      <dd class="active"><a href="#">Sve</a></dd>
      <dd><a href="#">Volontiraj</a></dd>
      <dd><a href="#">Doniraj</a></dd>
    </dl>
    <hr>
    <% @events.each do |e| %>
      <div class="row" id="<%=e.category%>">
        <div class="large-8 small-8 columns">
          <h5><%= link_to e.name, e %></h5>
        </div>
        <div class="large-4 small-4 columns">
          <span class="secondary label pull right"><%= e.category %></span>
        </div>
        <div class="large-12 small-4 columns">
          <p><%= e.grad %>
        </div>
        <div class="large-12 small-4 columns">
          <hr>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="row">
  <div class="large-12 small-12 columns">
    <h2 id="getting-started">Pomozite sebi i Vašim sugrađanima.</h2>
    <h4 class="subheader">Obratite se direktno i udružite sa drugim građanima i građankama.
      Vaše potrebe možete podvesti pod akcije institucija kojima verujete i pomoć dobiti i pre nego što očekujete.
      </h4>
    <hr>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <%= render 'form' %>
  </div>

app/views/events/show.html.erb
<div class="row">
  <div class="large-8 small-12 columns">
    <div class="row">
      <div class="small-8 large-8 columns">
        <h1><%= @event.name %></h1>
      </div>
      <div class="large-4 small-4 columns">
      <h1><%= link_to "Prijavi Se!", register_event_path, class: "small secondary button pull right"%></h1>
    </div>
  </div>
    <span class="label secondary"><%= @event.grad %></span>
    <span class="label success"><%= @event.category %></span>
    <div class="fb-share-button" data-href="http://www.volonter.rs/akcije/<%= @event.id %>" data-type="button_count"></div>

    <hr>
    <h3 class="subheader"><%= @event.description %></h3>
    <hr>
    <div class="fb-comments" data-href="http://www.volonter.rs/akcije/<%= @event.id %>" data-numposts="5" data-colorscheme="light"></div>


  </div>




<div class="large-4 small-12 columns">
  <img src="https://maps.googleapis.com/maps/api/staticmap?center=44.818441,20.3992720&zoom=14&size=400x400">
  <div class="hide-for-small panel">
    <h3><%= @event.date %></h3>
    <p>
      <%= @event.adresa %><br>
      <%= @event.grad %><br>
      <%= @event.telefon %>
</p>
    <a href="#" class="small secondary button">Kontakt</a>
    <%= link_to "Prijavi Se!", register_event_path, class: "small button"%>
  </div>
  <a href="#">
    <div class="panel callout radius">
      <h6><%= @event.registrations %> volontera prijavljeno</h6>
    </div></a>
  </div>

</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr>
    <div class="row">
      <div class="large-6 columns">
        <p>© Petar Ivacic 2014</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="http://floodhack.org">Floodhack</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=839288402765838&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">

    <li class="name">
      <h1>
        <%= link_to "VOLONTER", root_path %>
      </h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li><a href="#"><%= link_to "Nadji Akciju", root_path %></a></li>
      <li><a href="#"><%= link_to "Pokreni Akciju", new_event_path %></a></li>
    </ul>

    <ul class="right">
      <li class="has-button">
        <%= link_to "Pomozi", registracija_path, class: "small button" %>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/_navs.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">

    <li class="name">
      <h1>
        <%= link_to "VOLONTER", root_path %>
      </h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li><a href="#"><%= link_to "Nadji Akciju", root_path %></a></li>
      <li><a href="#"><%= link_to "Pokreni Akciju", new_event_path %></a></li>
    </ul>

    <ul class="right">
      <li class="has-dropdown">
          <a href="#"><%= link_to current_user.name %></a>
          <ul class="dropdown">
            <li>
              <a href="/signout" class="">Izloguj Se</a>
          </ul>
        </li>
      <li >
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:description" content="Odaberite aktuelnu akciju prema sopstvenim mogućnostima i pomozite Vašim sugrađanima.">
    <meta property="og:image" content="https://fbcdn-photos-b-a.akamaihd.net/hphotos-ak-xap1/t39.2081-0/p128x128/851593_839586439402701_281510653_n.png">

    <title><%= content_for?(:title) ? yield(:title) : "VOLONTER" %></title>
    <%= render 'layouts/head' %>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body id="fb-root">
    <% if current_user %>
      <%= render 'layouts/navs' %>
    <% else %>
      <%= render 'layouts/nav' %>
    <% end %>
    <div class="row">
      <p class="notice"><%= notice %></p>
    </div>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="row">
Volonter.RS je namenjen svima koji žele da traže i pruže potrebnu pomoć.<br>

Veb sajt www.Volonter.RS i aplikacija Volonter predstavljaju otvoreno platformu na kojoj svako može tražiti i ponuditi pomoć. Svako ko traži pomoć, pored drugih podataka, ostavlja lične podatke i nakom potvrde dobija e-mail sa linkom kojim se verifikuje kao osoba koja preuzima odgovornost za tačnost objavljenih podataka i samo izvođenje akcije.

Kontrolori tačnosti informacija i uspešnosti ste upravo vi volonteri pošto se svaka akcija na Facebook-u vodi kao "Događaj", a na Twitter-u kao xxxxx gde možete ostavljati vaše komentare. U slučaju lažne objave akcije i vaših komentara koji ukazuju na to, informacija se prosleđuje nadležnim državnim službama koje dalje preuzimaju slučaj i proveru informacija.

Pomoć možete dobiti i pre nego što očekujete. Nadležne institucije i organizacije prate objavljivanje vaših akcija i mogu vas kontaktirati i ponuditi pomoć a da imaju resurse koji su vama potrebni.

Sa akcija možete poneti zajedničko iskustvo i društvene mreže vam mogu pomoći da sačuvate te uspomene objavljivajuci fotografije sa akcija i razmenjujuci iskustva kroz komentare.
</div>

app/views/static_pages/feed.html.erb
<div class="row">
  <div class="large-4 columns">
    <section id="courses-banner-large">
      <div class="row">
        <div class="large-12 columns banner-image">
          <%= image_tag 'ikonica.png' %>
        </div>
        <div class="large-12 columns banner-info">
          <h3>Uključite se!</h3>
          <p>Odaberite aktuelnu akciju prema sopstvenim mogućnostima i pomozite Vašim sugrađanima.</p>
          <a href="#" class="button">Saznaj Vise »</a>
          <hr>
        </div>
      </div>
    </section>
  </div>
  <div class="large-8 small-12 columns">
    <dl class="sub-nav">
      <dt>Filter:</dt>
      <dd class="active"><a href="#">Sve</a></dd>
      <dd><a href="#">Volontiraj</a></dd>
      <dd><a href="#">Doniraj</a></dd>
    </dl>
    <hr>
    <% @events.each do |e| %>
      <div class="row" id="<%=e.category%>">
        <div class="large-8 small-8 columns">
          <h5><%= link_to e.name, e %></h5>
        </div>
        <div class="large-4 small-4 columns">
          <span class="secondary label pull right"><%= e.category %></span>
        </div>
        <div class="large-12 small-4 columns">
          <p><%= e.grad %>
        </div>
        <div class="large-12 small-4 columns">
          <hr>
        </div>
      </div>
    <% end %>
  </div>
</div>